### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'channel' of null - undefined:undefined"

### ISSUE THREAD

**Issue by crocodile** [AppGyver/supersonic#54]
I am always getting this error in the logs even when I run the example app unmodified.
(steroids create someapp -> cd someapp ->steroids connect)

AppGyver Steroids² 4.0.11
Chrome version: 40.0.2214.111

**Comment by harsaharsa** [comment]
Are you running on iOS or Android? Also, we're coordinating all issues at https://github.com/AppGyver/steroids/issues/, so please open a new ticket there – closing this one.
